# Generated by Django 2.2.7 on 2021-01-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicina',
            name='id',
        ),
        migrations.AddField(
            model_name='medicina',
            name='id_medicina',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
