# Generated by Django 2.2.7 on 2021-02-09 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
        ('medicamentos', '0003_auto_20210129_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicina',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorios.Laboratorio', verbose_name='Laboratorio'),
            preserve_default=False,
        ),
    ]
