# Generated by Django 2.2.7 on 2021-01-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='telefono_laboratorio',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
