# Generated by Django 2.2.7 on 2021-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0002_auto_20210128_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('dci', models.CharField(max_length=100, unique=True, verbose_name='DCI')),
                ('forma_farmaceutica', models.CharField(max_length=50, verbose_name='Forma Farmacéutica')),
                ('cantidad_unidades', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Medicina',
                'verbose_name_plural': 'Medicinas',
            },
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='autorizacion_laboratorio',
            field=models.CharField(max_length=200, verbose_name='Autorización'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='correo_laboratorio',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='direccion_laboratorio',
            field=models.TextField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nombre_laboratorio',
            field=models.CharField(max_length=100, unique=True, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='registro_laboratorio',
            field=models.CharField(max_length=200, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='telefono_laboratorio',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
    ]
