# Generated by Django 2.2.7 on 2021-01-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0003_auto_20210128_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distribuidor', models.CharField(max_length=50, unique=True, verbose_name='Nombre Destribuidor')),
                ('ruc_distribuidor', models.IntegerField(verbose_name='RUC')),
                ('direccion_distribuidor', models.CharField(max_length=50, verbose_name='Dirección')),
                ('ciudad_distribuidor', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('telefono_distribuidor', models.IntegerField(verbose_name='Teléfono')),
                ('correo_distribuidor', models.CharField(max_length=50, verbose_name='Correo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.AlterField(
            model_name='medicina',
            name='fecha_expiracion',
            field=models.DateField(verbose_name='Fecha de Expiración'),
        ),
        migrations.AlterField(
            model_name='medicina',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Unidad'),
        ),
    ]
