# Generated by Django 2.2.7 on 2021-01-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0004_auto_20210128_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicina',
        ),
    ]
