# Generated by Django 2.2.7 on 2021-02-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Pedido',
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='cantidad_venta',
            new_name='cantidad_pedida',
        ),
    ]
