# Generated by Django 2.2.7 on 2021-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(verbose_name='Cédula')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_cliente', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion_cliente', models.CharField(max_length=50, verbose_name='Dirección')),
                ('ciudad_cliente', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('telefono_cliente', models.IntegerField(verbose_name='teléfono')),
                ('correo_cliente', models.CharField(max_length=50, verbose_name='Correo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
