# Generated by Django 2.2.7 on 2021-02-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0001_initial'),
        ('medicamentos', '0003_auto_20210129_1141'),
        ('distribuidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_compra', models.IntegerField(verbose_name='Cantidad')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre_distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribuidores.Distribuidor', verbose_name='Nombre Distribuidor')),
                ('nombre_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.Laboratorio', verbose_name='Nombre Laboratorio')),
                ('nombre_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Medicina', verbose_name='Nombre Medicamento')),
            ],
        ),
    ]
