# Generated by Django 2.2.7 on 2021-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(max_length=100, unique=True, verbose_name='Laboratorio')),
                ('direccion_laboratorio', models.TextField(max_length=200, verbose_name='Dirección')),
                ('telefono_laboratorio', models.BigIntegerField(verbose_name='Teléfono')),
                ('correo_laboratorio', models.EmailField(max_length=254, verbose_name='Correo')),
                ('registro_laboratorio', models.CharField(max_length=200, verbose_name='Registro')),
                ('autorizacion_laboratorio', models.CharField(max_length=200, verbose_name='Autorización')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
    ]
