# Generated by Django 2.2.7 on 2021-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0002_auto_20210209_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='telefono_laboratorio',
            field=models.IntegerField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
